site_name: Suitcase
docs_dir: docs

plugins:
  - include-markdown

nav:
  - 'Home': 'index.md'
  - 'Getting started':
    - 'Install package': 'guide/installpackage.md'
    - 'Build from source': 'guide/buildsource.md'
    - 'Getting your HSM': 'guide/hsm.md'
