[project]
name = "suitcase"
authors = [{name = "Berry", email = "berry@halderen.net"}]
dynamic = ["version", "description"]

[project.optional-dependencies]
doc = [
    "sphinx~=4.2.0",
    "myst_parser",
    "nbsphinx",
]
